### ISSUE TITLE
Github Markdown에 이미지 업로드할 때

### ISSUE THREAD

**Issue by o-bard-o** [rbals0445/Smalltalk#1]
쓰시는 환경에 따라 다르겠지만 개인적으로 더 간편하게 할 수 있는 방법이 있어서 알려드려요!!

깃허브나 velog 마크다운 에디터에서 이미지를 드래드 앤 드랍하거나 복사 붙여넣기를 하면 자동으로 클라우드에 이미지가 올라가고 링크가 생성됩니다!

![](https://images.velog.io/images/dnr6054/post/70250a11-30f4-4b43-acbc-ef93cde6b735/image.png)
[https://images.velog.io/images/dnr6054/post/70250a11-30f4-4b43-acbc-ef93cde6b735/image.png](https://images.velog.io/images/dnr6054/post/70250a11-30f4-4b43-acbc-ef93cde6b735/image.png)

이런식으로요!

![](https://ko.javascript.info/article/closure/closure-variable-phrase.svg)

**Comment by rbals0445** [comment]
ㅋㅋㅋㅋㅋ 오!! 이런!! 좋네요
저 한번에 되는지 몰랐습니다.. 감사합니다!!!
